In [1]:
import numpy as np

#generate some random data
data = np.random.randn(2,3)
data

array([[-1.6493084 ,  0.81292348,  0.46703803],
       [ 0.07396087, -0.27423135, -0.17058509]])

In [8]:
#perform a mathematical operation on the data
print(f'data *10: {data *10}')
print()
print(f'data + data: {data + data}')
print()
print(f'data.dtype: {data.dtype}')


data *10: [[-16.49308404   8.12923483   4.67038035]
 [  0.73960867  -2.74231352  -1.7058509 ]]

data + data: [[-3.29861681  1.62584697  0.93407607]
 [ 0.14792173 -0.5484627  -0.34117018]]

data.dtype: float64


## Creating ndarrays

- easiest way to create an ndarray is to use the array function
- ![Table of Array Creation functions](./images/tableOfArrayCreationFunctions.png)

In [9]:
data1 = [6, 7.5, 8, 0, 1]
array1 = np.array(data1)
array1

array([6. , 7.5, 8. , 0. , 1. ])

In [19]:
#converting a nested sequence of equal-length lists into an ndarray

data2 = [
  [1,2,3,4],
  [5,6,7,8]
]
arr2 = np.array(data2)
arr2
print(f'arr2 {arr2}')
print(f'arr2 dimensions: {arr2.ndim} | arr2 shape: {arr2.shape}  arr2 data type: {arr2.dtype} ')

#create an array of zeros
arr3 = np.zeros(10)
arr4 = np.zeros((3,6))
print(arr3)
print()
print(arr4)


arr2 [[1 2 3 4]
 [5 6 7 8]]
arr2 dimensions: 2 | arr2 shape: (2, 4)  arr2 data type: int32 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [22]:
#create an empty numpy array
np.empty((2,3,2))

#create an array using np.arange

np.arange(15)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
#specifying data types
arr1 = np.array([1,2,3], dtype = np.float64)
arr3 = np.array([1,2,3], dtype = np.int32)

print(arr1.dtype)
print(arr3.dtype)

float64
int32


In [34]:
#casting an array from one type to another using ndarray's astype()

arr = np.array([1,2,3,4,5])
print(f'arr: {arr} | arr.dtype: {arr.dtype}')

float_arr = arr.astype(np.float64)
print(f'float_arr: {float_arr} | float_arr.dtype: {float_arr.dtype}')

arr1 = np.array([3.7,-1.2,-2.6,0.5, 12.9, 10.1])
print('---------------------------------------------------------------')

print(f'arr1: {arr1} | arr1.dtype: {arr1.dtype}')
int_arr1 = arr1.astype(np.int32)
print(f'float_arr1: {int_arr1} | float_arr1.dtype: {int_arr1.dtype}')

#converting an array of string into float
numeric_strings =np.array(['1.25', '-9.6', '42'], dtype = np.string_)
print('---------------------------------------------------------------')
print(f'numeric string:{numeric_strings}')
numeric_strings_to_float = numeric_strings.astype(float)
print(f'numeric string to float:{numeric_strings_to_float}')


arr: [1 2 3 4 5] | arr.dtype: int32
float_arr: [1. 2. 3. 4. 5.] | float_arr.dtype: float64
---------------------------------------------------------------
arr1: [ 3.7 -1.2 -2.6  0.5 12.9 10.1] | arr1.dtype: float64
float_arr1: [ 3 -1 -2  0 12 10] | float_arr1.dtype: int32
---------------------------------------------------------------
numeric string:[b'1.25' b'-9.6' b'42']
numeric string to float:[ 1.25 -9.6  42.  ]


In [ ]:
#Arithmetic with NumPy Arrays